

### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "abc2@gmail.com",
    "password":"1234567nd"
}
### Get current user
GET http://localhost:3000/auth/whoami

### Logout 
POST http://localhost:3000/auth/signout
### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "abc2@gmail.com",
    "password":"1234567nd"
}

### find a user by id
GET  http://localhost:3000/auth/1

### find all users with given email
GET  http://localhost:3000/auth/?email=abc1@gmail.com

### Update a user with given id
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "abc1@gmail.com",
    "password":"123456780nd"
}

### Delete user with given id
DELETE http://localhost:3000/auth/3
