## Create report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "toyota",
    "model": "corolla",
    "year": 1999,
    "mileage": 100000,
    "lng": 0 ,
    "lat": 0,
    "price": 100000
}
### Approve an report
PATCH http://localhost:3000/reports/3
Content-Type: application/json

{
    "approved": true
}

### Get an estimate for an existing vehicle
GET http://localhost:3000/reports?make=toyota&model=corolla&lng=0&lat=0&mileage=20000&year=1980